services:
  - name: renderapp
    type: web
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: mysql://user:password@mysql:3306/dbname
    ports:
      - 8080

databases:
  - name: mysql
    plan: free
    databaseName: dbname
    user: user
    diskSizeGB: 2
