services:
  - name: renderapp
    build:
      dockerfile: Dockerfile
    routes:
      - url: /
    port: 8080

  - type: pserv
    name: mysql
    plan: free
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 2
